name: Build and Push Docker Image to Docker Hub

on:
  schedule:
    - cron: "0 */6 * * *" # Vérifie toutes les 6 heures
  workflow_dispatch: # Permet de lancer manuellement le workflow

permissions:
  contents: read       # Lire les fichiers nécessaires au build

env:
  DOCKER_USERNAME: your_dockerhub_username # Remplacez par votre nom d'utilisateur Docker Hub
  IMAGE_NAME: your_dockerhub_username/repository_name # Remplacez par votre image (nom d'utilisateur + nom de l'image)

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Cloner le dépôt contenant le Dockerfile
      - name: Checkout repository
        uses: actions/checkout@v3

      # Étape 2 : Debug - Vérifier les fichiers présents
      - name: Check for Dockerfile
        run: |
          echo "Liste des fichiers dans le répertoire courant :"
          ls -la
          if [ ! -f Dockerfile ]; then
            echo "Erreur : Dockerfile introuvable dans le contexte actuel."
            exit 1
          fi

      # Étape 3 : Configurer Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Étape 4 : Connexion à Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PAT }}

      # Étape 5 : Construire et pousser l'image Docker
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: .                           # Contexte de build (dossier courant)
          push: true                           # Pousser l'image après le build
          tags: ${{ env.IMAGE_NAME }}:latest
