name: Auto-build Docker Image on Source Repo Update

on:
  schedule:
    # Vérifie les mises à jour toutes les 6 heures
    - cron: "0 */6 * * *"
  workflow_dispatch: # Permet de lancer le workflow manuellement

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Cloner le dépôt source
      - name: Clone source repository
        run: |
          git clone https://github.com/Th0rum/SuperBin.git source-repo
          cd source-repo
          git fetch --tags

      # Étape 2 : Connexion à GHCR (registre GitHub Container Registry)
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      # Étape 3 : Construire l'image Docker depuis le dépôt source
      - name: Build Docker image
        run: |
          cd source-repo
          docker build -t ghcr.io/${{ github.repository_owner }}/superbin:latest .

      # Étape 4 : Pousser l'image vers GHCR
      - name: Push Docker image
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/superbin:latest
