name: Build and Push Docker Image

on:
  schedule:
    - cron: "0 */6 * * *" # Vérifie toutes les 6 heures
  workflow_dispatch: # Permet de lancer manuellement le workflow

permissions:
  contents: read       # Lire les fichiers nécessaires au build
  packages: write      # Publier l'image Docker sur GHCR

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Configurer Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Étape 2 : Connexion à GitHub Container Registry
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      # Étape 3 : Construire et pousser l'image Docker
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: .                           # Contexte de build (le répertoire courant)
          push: true                           # Pousser l'image après le build
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
