name: Build and Push Docker Image to GitHub Container Registry

on:
  push:
    branches:
      - main  # Déclenche le workflow pour les commits sur la branche main
  workflow_dispatch:  # Permet de lancer manuellement le workflow

permissions:
  contents: write  # Nécessaire pour récupérer le dépôt
  packages: write  # Nécessaire pour publier l'image sur GHCR

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Récupérer le dépôt
      - name: Checkout repository
        uses: actions/checkout@v3

      # Étape 2 : Connexion à GitHub Container Registry
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      # Étape 3 : Construire l'image Docker
      - name: Build Docker image
        run: |
          docker build -t ghcr.io/dextouu/superbin:latest .

      # Étape 4 : Pousser l'image vers GHCR
      - name: Push Docker image
        run: |
          docker push ghcr.io/dextouu/superbin:latest
