name: Auto-build Docker Image on Source Repo Update

on:
  schedule:
    # Vérifie les mises à jour toutes les 6 heures
    - cron: "0 */6 * * *"
  workflow_dispatch: # Permet de lancer le workflow manuellement

permissions:
  contents: write
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Cloner le dépôt source
      - name: Clone source repository
        run: |
          git clone https://github.com/Th0rum/SuperBin.git source-repo
          cd source-repo
          git fetch --tags

      # Étape 2 : Connexion à GHCR
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      # Étape 3 : Construire et pousser l'image Docker
      - name: Build and Push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./source-repo
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/superbin:latest

      # Étape 4 : Tester le pull public
      - name: Test public Docker pull
        run: |
          docker logout ghcr.io
          docker pull ghcr.io/${{ github.repository_owner }}/superbin:latest
