
name: Build and Push Docker Image

on:
  schedule:
    - cron: "0 */6 * * *" # Vérifie toutes les 6 heures
  workflow_dispatch: # Permet de lancer manuellement le workflow

permissions:
  contents: read       # Lire les fichiers nécessaires au build
  packages: write      # Publier l'image Docker sur GHCR

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Cloner le dépôt contenant le Dockerfile
      - name: Checkout repository
        uses: actions/checkout@v3

      # Étape 2 : Configurer l'identité Git (si nécessaire)
      - name: Configure Git Identity
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

      # Étape 3 : Connexion à GitHub Container Registry
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      # Étape 4 : Extraire les métadonnées (tags et labels)
      - name: Extract metadata for Docker
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      # Étape 5 : Construire et pousser l'image Docker
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .                           # Contexte de build (le répertoire courant)
          push: true                           # Pousser l'image après le build
          tags: ${{ steps.Extract-metadata-for-Docker.outputs.tags }} # Tags générés
          labels: ${{ steps.Extract-metadata-for-Docker.outputs.labels }} # Labels générés

      # Étape 6 : Tester le pull public
      - name: Test public Docker pull
        run: |
          docker logout ghcr.io
          docker pull ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
