name: Sync external repository to this repository

on:
  schedule:
    - cron: "0 */6 * * *" # Vérifie toutes les 6 heures
  workflow_dispatch: # Permet de lancer manuellement le workflow

permissions:
  contents: write       # Nécessaire pour écrire dans ton dépôt
  metadata: read        # Nécessaire pour accéder aux informations publiques du dépôt

jobs:
  sync-repo:
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Cloner le dépôt source
      - name: Clone external repository
        run: |
          git clone https://github.com/Th0rum/SuperBin.git external-repo
          cd external-repo
          git fetch --tags

      # Étape 2 : Cloner ton propre dépôt
      - name: Checkout this repository
        uses: actions/checkout@v3
        with:
          ref: main # Branche principale de ton dépôt

      # Étape 3 : Synchroniser les fichiers
      - name: Sync files from external to this repository
        run: |
          rsync -av --delete external-repo/ ./ # Synchronisation des fichiers
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          if [[ -n "$(git status --porcelain)" ]]; then
            git add .
            git commit -m "Sync from external repository"
            git push
          else
            echo "No changes detected. Skipping commit."
          fi

      # Étape 4 : Debug - Vérifier les fichiers après synchronisation
      - name: List synchronized files
        run: |
          echo "Liste des fichiers après synchronisation :"
          ls -la
